# Generated by Django 3.2.8 on 2021-10-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('q_a_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
    ]
